module processor.ktx;

import processor.base;

/**
 *  Create loader for KTX-Software.   
 *  @see https://github.com/KhronosGroup/KTX-Software
 *
 *  WIP - unfinished
 */
final class KtxProcessor : Processor {
private:
    EConfig config;
    Extractor extractor;
    Emitter emitter;
    enum vulkanVersion = "1.4.350.0";
    enum ktxVersion    = "5.0.0";
    enum dllName       = "ktx-%s.dll".format(ktxVersion);
    enum srcPath       = "C:/Temp/KTX-Software-5.0.0-rc1/";
public:
    override void process() {
        prepare();

        string mainInclude = srcPath ~ "lib/include/ktxvulkan.h";

        parse(Filepath(mainInclude));
        extract();
    	emit();
    }
protected:
    override void adjustDefines(ref string[string] defines) {
        defines["VK_USE_PLATFORM_WIN32_KHR"] = "1";
    }
    override void adjustIncludes(ref string[] includeDirs) {
        string vulkanH = getVulkanSdkDirectory() ~ "/Include/";
        includeDirs ~= vulkanH;
        includeDirs ~= srcPath ~ "lib/include";
        includeDirs ~= srcPath ~ "external/dfdutils";
        //includeDirs ~= srcPath ~ "other_include";
    }
private:
    string getVulkanSdkDirectory() {
        string vulkanSdk = environment.get("VULKAN_SDK");
        if(vulkanSdk is null) {
            vulkanSdk = "C:\\work\\VulkanSDK\\%s".format(vulkanVersion);
        }
        return vulkanSdk;
    }
    void extract() {
        this.config = new EConfig();

        config.requiredFunctionRegexes ~= [
            regex(r"^ktx.*$")
        ];
        config.requiredTypeRegexes ~= [
            regex(r"^ktx.*$")
        ];
        config.requiredTypedefRegexes = [
            regex(r"^PFN_ktx.*$")
        ];
        // config.excludeRegexes ~= [
        //     regex(r"^(HINSTANCE|HMONITOR|HWND)$"),
        //     regex(r".*(__security_cookie|GUID).*")
        // ];

        config.excludeRegexes = [ 
            regex(r"^(Vk|vk).*"),
            regex(r"HWND"),
            regex(r"^GUID$")
        ];

        this.extractor = new Extractor(config);
        extractor.process(parent);
    }
    void emit() {
        enum string[] COMMENTS = [
            "KTX-Software %s Include file converted to D (This is a generated file)".format(ktxVersion),
            "",
            "Generated by CTools (https://github.com/pvmoore/dlang-CTools)",
            "",
            "Usage:",
            "  ** Start program",
            "  KTXLoader.load();",
            "  ** ",
            "  KTXLoader.unload();",
            "  ** Exit program"
        ];


        string[] privateImports =[
            "vulkan.api.vulkan_api"
        ];

        string[string] extraDefs; 
        string[string] extraAliases;

        writefln("emitting...");

        import std : map, array;
        auto loader = new EmitDLLLoader("KTXLoader", dllName, false)
            .loadFunctions(getOrderedValues(extractor.funcDecls)
                                              .map!(it=>it.name)
                                              .array);

        auto flags = Emitter.Flag.UNQUALIFIED_ENUM | Emitter.Flag.QUALIFIED_ENUM;

        this.emitter = new Emitter(extractor, "ktx_api", flags)
            .privateImports(privateImports)
            .extraDefinitions(extraDefs)
            .extraAliases(extraAliases);

        emitter.add(new Comment(COMMENTS));

        emitter.add(loader);

        emitter.emitTo("generated/ktx_api.d");
    }
}
