module processor.vma;

import processor.base;

/**
 * WIP Unfinished
 */
final class VmaProcessor : Processor {
private:
    EConfig config;
    Extractor extractor;
    Emitter emitter;
    enum vulkanVersion = "1.4.350.0";
    enum vmaVersion    = "3.4.0";
    enum dllName       = "vma-%s.dll".format(vmaVersion);
public:
    override void process() {
        prepare();

        string vk_mem_alloc_h = getVulkanSdkDirectory() ~ "/Include/vma/vk_mem_alloc.h";

        parse(Filepath(vk_mem_alloc_h));
        extract();
    	emit();
    }
protected:
    override void adjustDefines(ref string[string] defines) {
        defines["VMA_VULKAN_VERSION"] = "1004000";  // 1.4

        // Vulkan 1.1
        defines["VMA_DEDICATED_ALLOCATION"] = "1";  // VK_KHR_get_memory_requirements2 && VK_KHR_dedicated_allocation
        defines["VMA_BIND_MEMORY2"] = "1";          // VK_KHR_bind_memory2
        defines["VMA_MEMORY_BUDGET"] = "1";         // VK_EXT_memory_budget && (VK_KHR_get_physical_device_properties2 || VMA_VULKAN_VERSION >= 1001000)
        defines["VMA_EXTERNAL_MEMORY"] = "1";       // VK_KHR_external_memory
        defines["VMA_EXTERNAL_MEMORY_WIN32"] = "1"; // VK_KHR_external_memory_win32

        // Vulkan 1.2
        defines["VMA_BUFFER_DEVICE_ADDRESS"] = "1"; // VK_KHR_buffer_device_address || VMA_VULKAN_VERSION >= 1002000

        // Not guaranteed but Probably available :)
        defines["VMA_MEMORY_PRIORITY"] = "1";       // VK_EXT_memory_priority

        // Vulkan 1.3
        defines["VMA_KHR_MAINTENANCE4"] = "1";      // VK_KHR_maintenance4

        // Vulkan 1.4
        defines["VMA_KHR_MAINTENANCE5"] = "1";      // VK_KHR_maintenance5

        defines["VK_USE_PLATFORM_WIN32_KHR"] = "1";
    }
    override void adjustIncludes(ref string[] includeDirs) {
        string vulkanH = getVulkanSdkDirectory() ~ "/Include/";
        includeDirs ~= vulkanH;
    }
private:
    string getVulkanSdkDirectory() {
        string vulkanSdk = environment.get("VULKAN_SDK");
        if(vulkanSdk is null) {
            vulkanSdk = "C:\\work\\VulkanSDK\\%s".format(vulkanVersion);
        }
        return vulkanSdk;
    }
    void extract() {
        this.config = new EConfig();

        config.requiredFunctionRegexes ~= [
            regex(r"^vma.*$")
        ];
        config.requiredTypeRegexes ~= [
            regex(r"^Vma.*$")
            //regex(r"^Std.*")
        ];
        config.requiredTypedefRegexes = [
            regex(r"^(PFN_vma|Vk).*$")
        ];
        // config.excludeRegexes ~= [
        //     regex(r"^(HINSTANCE|HMONITOR|HWND)$"),
        //     regex(r".*(__security_cookie|GUID).*")
        // ];

        config.excludeRegexes = [ 
            regex(r"^(Vk|vk).*"),
            regex(r"HWND"),
            regex(r"^GUID$")
        ];

        this.extractor = new Extractor(config);
        extractor.process(parent);
    }
    void emit() {
        enum string[] COMMENTS = [
            "Vulkan Memory Allocator %s Include file converted to D (This is a generated file)".format(vmaVersion),
            "",
            "Generated by CTools (https://github.com/pvmoore/dlang-CTools)",
            "",
            "Usage:",
            "  ** Start program",
            "  VMALoader.load();",
            "  ** ",
            "  VMALoader.unload();",
            "  ** Exit program"
        ];


        string[] privateImports =[
            "vulkan_api"
        ];

        string[string] extraDefs; // = [
            // "VK_NULL_HANDLE" : "null",
            // "VK_TRUE" : "1",
            // "VK_FALSE" : "0",
            // "VK_QUEUE_FAMILY_IGNORED" : "(~0U)",
            // "VK_REMAINING_MIP_LEVELS" : "(~0U)",
            // "VK_REMAINING_ARRAY_LAYERS" : "(~0U)",
            // "VK_SUBPASS_EXTERNAL" : "(~0U)",
            // "VK_WHOLE_SIZE" : "(~0UL)",
            // "VK_SHADER_UNUSED_KHR" : "(~0U)"
        //];
        string[string] extraAliases;

        writefln("emitting...");

        //writefln("funcDecls: %s", getOrderedValues(extractor.funcDecls));
        // writefln("funcDefs: %s", extractor.funcDefs);
        // writefln("enums: %s", extractor.enums);
        // writefln("structDefs: %s", extractor.structDefs);
        // writefln("aliases: %s", extractor.aliases);
        // writefln("typedefs: %s", extractor.typedefs);
        // writefln("vars: %s", extractor.vars);

        import std : map, array;
        auto loader = new EmitDLLLoader("VMALoader", dllName)
            .loadFunctions(getOrderedValues(extractor.funcDecls)
                                              .map!(it=>it.name)
                                              .array);

        auto flags = Emitter.Flag.UNQUALIFIED_ENUM | Emitter.Flag.QUALIFIED_ENUM;

        this.emitter = new Emitter(extractor, "vma_api", flags)
            .privateImports(privateImports)
            .extraDefinitions(extraDefs)
            .extraAliases(extraAliases);

        emitter.add(new Comment(COMMENTS));

        emitter.add(loader);

        emitter.emitTo("generated/vma_api.d");
    }
}
